# Harmony Jekyll theme general configurations 

# Base URL
baseurl: ""

# Localhost 
url: http://127.0.0.1:4000

# Site live URL
#url: http://blakemerryman.github.io

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Blake Merryman
  # Little description about your site
  description: My thoughts & ideas.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  #meta_description: > ...
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Blake Merryman
    email: blake.merryman@gmail.com
    url:  http://blakemerryman.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: blakemerryman
    twitter: blakemerryman 
    facebook: 
    gplus: 
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor
  
# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
